import { AppBar, Toolbar, Typography } from '@mui/material';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Tadreebi',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppBar
          position="static"
          sx={{ boxShadow: 'none', padding: 0, borderBottom: '1px solid #e0e0e0' }}
        >
          <Toolbar sx={{ bgcolor: 'white' }}>
            <Typography
              variant="h6"
              component="div"
              sx={{ flexGrow: 1, color: 'black', fontWeight: 'bold', fontSize: 24 }}
            >
              Tadreebi
            </Typography>
          </Toolbar>
        </AppBar>
        {children}
      </body>
    </html>
  );
}
